import {
  CloudRain,
  Gauge,
  HardHat,
  MapPin,
  Route,
  ShieldAlert,
  Truck,
  Waves,
} from "lucide-react";
import type { DashboardData } from "@/features/dashboard/types";

/**
 * Static mock dataset for the National Operations Center dashboard.
 * Separated from the service so components never hardcode operational values.
 */
export const MOCK_DASHBOARD_DATA: DashboardData = {
  lastUpdated: new Date().toISOString(),
  map: {
    longitude: 121.0244,
    latitude: 14.5995,
    zoom: 11.4,
    bearing: 12,
    scaleLabel: "2 km",
  },
  kpis: [
    {
      id: "incidents",
      label: "Active Flood Incidents",
      value: 23,
      icon: Waves,
      trend: "up",
      dailyChange: 4,
      dailyChangeLabel: "+4 today",
      status: "critical",
      sparkline: [12, 14, 13, 16, 18, 20, 23],
    },
    {
      id: "critical-areas",
      label: "Critical Areas",
      value: 17,
      icon: ShieldAlert,
      trend: "up",
      dailyChange: 2,
      dailyChangeLabel: "+2 today",
      status: "warning",
      sparkline: [10, 11, 12, 13, 14, 16, 17],
    },
    {
      id: "flood-prone",
      label: "Flood-Prone Areas",
      value: 142,
      icon: MapPin,
      trend: "flat",
      dailyChange: 0,
      dailyChangeLabel: "No change",
      status: "normal",
      sparkline: [142, 142, 141, 142, 142, 142, 142],
    },
    {
      id: "equipment",
      label: "Equipment Deployed",
      value: 86,
      icon: Truck,
      trend: "up",
      dailyChange: 12,
      dailyChangeLabel: "+12 today",
      status: "success",
      sparkline: [58, 62, 68, 71, 74, 80, 86],
    },
    {
      id: "road-closures",
      label: "Road Closures",
      value: 9,
      icon: Route,
      trend: "down",
      dailyChange: -3,
      dailyChangeLabel: "−3 today",
      status: "warning",
      sparkline: [14, 13, 12, 11, 10, 10, 9],
    },
    {
      id: "rainfall-stations",
      label: "Rainfall Stations",
      value: 48,
      icon: CloudRain,
      trend: "up",
      dailyChange: 1,
      dailyChangeLabel: "+1 online",
      status: "success",
      sparkline: [44, 45, 45, 46, 47, 47, 48],
    },
    {
      id: "water-sensors",
      label: "Water-Level Sensors",
      value: 112,
      icon: Gauge,
      trend: "up",
      dailyChange: 3,
      dailyChangeLabel: "+3 online",
      status: "success",
      sparkline: [98, 100, 102, 105, 108, 110, 112],
    },
    {
      id: "projects",
      label: "Active Projects",
      value: 34,
      icon: HardHat,
      trend: "flat",
      dailyChange: 0,
      dailyChangeLabel: "No change",
      status: "normal",
      sparkline: [34, 34, 33, 34, 34, 34, 34],
    },
  ],
  incidents: [
    {
      id: "inc-001",
      title: "Waist-deep flooding — EDSA-Kamuning",
      location: "Quezon City, NCR",
      timestamp: "14:32 PHT",
      priority: "critical",
      status: "Active",
      statusTone: "critical",
    },
    {
      id: "inc-002",
      title: "Overflowing creek — Marikina River",
      location: "Marikina City, NCR",
      timestamp: "14:18 PHT",
      priority: "critical",
      status: "Monitoring",
      statusTone: "critical",
    },
    {
      id: "inc-003",
      title: "Urban flooding — C5-Bicutan",
      location: "Parañaque City, NCR",
      timestamp: "13:55 PHT",
      priority: "high",
      status: "Active",
      statusTone: "warning",
    },
    {
      id: "inc-004",
      title: "Drainage blockage — Roxas Blvd.",
      location: "Manila, NCR",
      timestamp: "13:41 PHT",
      priority: "high",
      status: "Response",
      statusTone: "warning",
    },
    {
      id: "inc-005",
      title: "Flash flood alert — San Mateo",
      location: "Rizal Province",
      timestamp: "13:12 PHT",
      priority: "medium",
      status: "Watch",
      statusTone: "normal",
    },
  ],
  criticalAreas: [
    {
      id: "ca-001",
      title: "Marikina River — Sto. Niño Bridge",
      location: "Marikina City",
      timestamp: "14:25 PHT",
      priority: "critical",
      status: "Level 3",
      statusTone: "critical",
    },
    {
      id: "ca-002",
      title: "Tullahan River — NLEX crossing",
      location: "Valenzuela City",
      timestamp: "14:10 PHT",
      priority: "high",
      status: "Level 2",
      statusTone: "warning",
    },
    {
      id: "ca-003",
      title: "Pasig River — C-5 junction",
      location: "Pasig City",
      timestamp: "13:48 PHT",
      priority: "high",
      status: "Level 2",
      statusTone: "warning",
    },
  ],
  fieldReports: [
    {
      id: "fr-001",
      title: "Pump station operational — QC District 3",
      location: "Quezon City",
      timestamp: "14:28 PHT",
      priority: "medium",
      status: "Submitted",
      statusTone: "success",
    },
    {
      id: "fr-002",
      title: "Debris cleared — C.P. Garcia Ave.",
      location: "Taguig City",
      timestamp: "14:05 PHT",
      priority: "low",
      status: "Verified",
      statusTone: "success",
    },
    {
      id: "fr-003",
      title: "Sandbag deployment complete — Malabon",
      location: "Malabon City",
      timestamp: "13:30 PHT",
      priority: "medium",
      status: "Submitted",
      statusTone: "normal",
    },
  ],
  roadClosures: [
    {
      id: "rc-001",
      title: "EDSA northbound — Kamuning to Timog",
      location: "Quezon City",
      timestamp: "14:20 PHT",
      priority: "critical",
      status: "Closed",
      statusTone: "critical",
    },
    {
      id: "rc-002",
      title: "C-5 southbound — Bicutan interchange",
      location: "Parañaque City",
      timestamp: "13:50 PHT",
      priority: "high",
      status: "Closed",
      statusTone: "warning",
    },
    {
      id: "rc-003",
      title: "Roxas Blvd. — Padre Faura",
      location: "Manila",
      timestamp: "13:15 PHT",
      priority: "medium",
      status: "Partial",
      statusTone: "warning",
    },
  ],
  weather: {
    region: "Metro Manila (NCR)",
    temperature: 28,
    temperatureUnit: "°C",
    rainfall: 18.4,
    rainfallUnit: "mm/hr",
    windSpeed: 32,
    windUnit: "km/h",
    humidity: 87,
    stormStatus: "Tropical Depression — Enhanced Southwest Monsoon",
    stormTone: "warning",
    updatedAt: "14:35 PHT",
  },
  equipment: {
    total: 124,
    available: 28,
    deployed: 86,
    maintenance: 10,
    utilizationPercent: 69,
  },
  systemHealth: [
    { id: "gis", label: "GIS Engine", status: "online" },
    { id: "sensors", label: "Sensor Network", status: "online" },
    { id: "comms", label: "Field Comms", status: "online" },
  ],
  alerts: [
    {
      id: "alert-001",
      title: "Critical water level — Marikina River",
      message: "Water level exceeded Alert Level 3 threshold at Sto. Niño Bridge.",
      severity: "critical",
      location: "Marikina City",
      timestamp: "14:30 PHT",
    },
    {
      id: "alert-002",
      title: "Heavy rainfall warning",
      message: "PAGASA: Intense rainfall expected in NCR within the next 2 hours.",
      severity: "warning",
      location: "NCR",
      timestamp: "14:15 PHT",
    },
    {
      id: "alert-003",
      title: "Pump station activated",
      message: "QC District 3 pump station auto-activated due to rising water levels.",
      severity: "info",
      location: "Quezon City",
      timestamp: "14:02 PHT",
    },
    {
      id: "alert-004",
      title: "Road reopened — C.P. Garcia Ave.",
      message: "Flood subsided. Lane restrictions lifted.",
      severity: "resolved",
      location: "Taguig City",
      timestamp: "13:45 PHT",
    },
  ],
  notifications: [
    {
      id: "notif-001",
      title: "Equipment dispatch confirmed",
      message: "2 amphibious excavators en route to Marikina River sector.",
      severity: "info",
      timestamp: "14:28 PHT",
    },
    {
      id: "notif-002",
      title: "District engineer report received",
      message: "Field assessment submitted for EDSA-Kamuning corridor.",
      severity: "info",
      timestamp: "14:12 PHT",
    },
    {
      id: "notif-003",
      title: "Sensor threshold breach",
      message: "Water-level sensor WL-042 exceeded warning threshold.",
      severity: "warning",
      timestamp: "13:58 PHT",
    },
  ],
  activity: [
    {
      id: "act-001",
      time: "14:32",
      category: "flood",
      title: "Flood reported",
      description: "Waist-deep flooding reported at EDSA-Kamuning intersection.",
      priority: "critical",
    },
    {
      id: "act-002",
      time: "14:28",
      category: "equipment",
      title: "Equipment dispatched",
      description: "2 amphibious excavators deployed to Marikina River sector.",
      priority: "high",
    },
    {
      id: "act-003",
      time: "14:22",
      category: "weather",
      title: "Rainfall increased",
      description: "Rainfall intensity rose to 18.4 mm/hr across Metro Manila.",
      priority: "high",
    },
    {
      id: "act-004",
      time: "14:15",
      category: "water",
      title: "Water level rising",
      description: "Marikina River at Sto. Niño Bridge exceeded Alert Level 3.",
      priority: "critical",
    },
    {
      id: "act-005",
      time: "14:05",
      category: "road",
      title: "Road reopened",
      description: "C.P. Garcia Avenue flood clearance complete — lanes restored.",
      priority: "medium",
    },
    {
      id: "act-006",
      time: "13:48",
      category: "report",
      title: "Engineer submitted report",
      description: "District engineer filed field assessment for C-5 Bicutan corridor.",
      priority: "medium",
    },
    {
      id: "act-007",
      time: "13:30",
      category: "system",
      title: "Pump station activated",
      description: "QC District 3 pump station auto-activated by sensor trigger.",
      priority: "low",
    },
    {
      id: "act-008",
      time: "13:12",
      category: "flood",
      title: "Flash flood alert",
      description: "San Mateo creek overflow warning issued for downstream areas.",
      priority: "high",
    },
  ],
};

/** Simulated network latency for the mock dashboard service. */
export const MOCK_DASHBOARD_LATENCY_MS = 280;
