import {
  LayoutDashboard,
  Waves,
  Droplets,
  Gauge,
  CloudRain,
  FileBarChart,
  Users,
  Settings,
  Bell,
  CircleCheck,
  CircleX,
  TriangleAlert,
  Info,
  Search,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  Route,
  Mountain,
  GitBranch,
  Network,
  BarChart3,
  Maximize,
  Minimize,
  Wifi,
  WifiOff,
  PanelRightClose,
  PanelRightOpen,
  Inbox,
  BrainCircuit,
  Archive,
  HardHat,
  type LucideIcon,
} from "lucide-react";

/**
 * Central icon registry. Referencing icons by semantic key (instead of importing
 * Lucide ad-hoc) keeps iconography consistent and swappable in one place.
 */
export const AppIcons = {
  dashboard: LayoutDashboard,
  floodMonitoring: Waves,
  floodProne: Droplets,
  drainages: Network,
  pumpingStations: Gauge,
  weather: CloudRain,
  reports: FileBarChart,
  reportsIncoming: Inbox,
  reportsAiSummary: BrainCircuit,
  reportsArchive: Archive,
  analytics: BarChart3,
  incidents: AlertTriangle,
  roads: Route,
  riverBasin: Mountain,
  waterways: GitBranch,
  users: Users,
  operations: HardHat,
  settings: Settings,
  notifications: Bell,
  success: CircleCheck,
  error: CircleX,
  warning: TriangleAlert,
  info: Info,
  search: Search,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  fullscreen: Maximize,
  exitFullscreen: Minimize,
  wifi: Wifi,
  wifiOff: WifiOff,
  utilityPanelOpen: PanelRightOpen,
  utilityPanelClose: PanelRightClose,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof AppIcons;
